name: kure
description: "App for Managing medical appointments"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  async: ^2.13.0
  flutter:
    sdk: flutter
  material_color_utilities: ^0.11.1
  provider: ^6.1.5
  vm_service: ^15.0.0
  intl: ^0.18.1
  mask_text_input_formatter: ^2.9.0
  custom_radio_grouped_button: ^2.2.1
  sqflite: ^2.4.2
  path: ^1.9.1
  sqflite_common_ffi: ^2.3.5
  universal_io: ^2.2.2
  http: ^1.4.0
  currency_textfield: ^4.14.1
  fl_chart: ^0.65.0
  flutter_launcher_icons: ^0.14.3
  searchable_listview: ^2.17.3

## dev_dependencies:
##  flutter_test:
##    sdk: flutter
##  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/

intl: any
provider: ^5.0.0

flutter_launcher_icons:
  image_path_android: "images/icon.png"
  image_path_ios: "images/icon.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "images/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "images/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "images/icon.png"


